name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: sudo apt install tree texlive texlive-latex-extra texlive-fonts-extra texlive-lang-cyrillic biber latexmk

    - name: Build
      run: make

    - name: Deploy
      run: |
        echo '${{ secrets.SFTP_KEY }}' > ssh_id
        chmod 600 ssh_id
        echo 'cd ${{ secrets.SFTP_ROOT }}
              put anthology.pdf
        ' | sftp -i ssh_id -o StrictHostKeyChecking=no -o Port=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}
