name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make
          make

    - name: Deploy
      run: |
        echo '${{ secrets.SFTP_KEY }}' > ssh_id
        chmod 600 ssh_id
        echo 'cd ${{ secrets.SFTP_ROOT }}
              put notebook.pdf
        ' | sftp -i ssh_id -o StrictHostKeyChecking=no -o Port=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}
